Repository Anon-Planet/thgtoa, pull requests merged in 2022-09, with the labels that each got.

#225 Cleanup README file links
  README.md
Labels: low priority

#221 Minimize .gitignore file
  .gitignore
Labels: low priority

#222 Fix typo in issue template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: low priority

#224 Clean links page
  links.md
Labels: low priority

#234 Update verify.md
  verify.md
Labels: documentation, Information Update

#236 Update Appendix V1 regarding Brave Browser settings
  guide.md
Labels: documentation, Information Update

#237 Added my donation for the VPS upgrade
  donations.md
Labels: medium priority, Information Update, New Information, Review request

#243 Small useless content deletion
  guide.md
Labels: medium priority, Delete information, Review request

#244 Adding (reviewed/approved by LINDDUN designers) quick tutorial video link
  guide.md
Labels: medium priority, Information Update, New Information, Review request

#247 Fix typo in Leakuidator
  guide.md
Labels: low priority, doc.t

#246 Update about page
  about.md
Labels: documentation, Information Update, Delete information
