Repository Anon-Planet/thgtoa, pull requests merged in 2022-08, with the labels that each got.

#182 Update on Tor Browser
  guide.md
  media/image54.jpeg
  media/image54.png
  media/image55.jpeg
  media/image55.png
  media/image56.jpeg
  media/image56.png
  media/image57.jpeg
  media/image57.png
Labels: documentation, medium priority

#183 Move to 1.1.6pre1
  CHANGELOG.md
  _layouts/default.html
  guide.md
Labels: medium priority, Information Update, Review request

#153 Add tor mirror url to readme and guide
  README.md
  _config.yml
  guide.md
Labels: enhancement, high priority, Review request

#162 Small fix in the "pay with crypto section"
  guide.md
Labels: medium priority, Information Update, Review request

#149 Appendix L: list format, make it easier to skim through
  guide.md
Labels: documentation, enhancement, medium priority

#189 Fixed wrong e-mail on about page
  about.md
Labels: high priority, Information Update, New Information, Review request

#201 Micro-architectural bugs in Intel and AMD CPUs
  guide.md
Labels: documentation

#199 Update on browser side-channel attack section
  guide.md
Labels: high priority, Information Update, New Information, Review request

#198 Update (current) chatroom rules to add #OSINT
  chatrooms-rules.md
Labels: high priority, Information Update, New Information, Review request

#202 Update bad link Appendix R
  guide.md
Labels: high priority, Review request, Bad Link

#187 Update of the threat modeling appendix (B3)
  guide.md
  media/image59.png
Labels: help wanted, medium priority, Information Update, New Information, Delete information, Review request

#196 Adding mention of OSINT room in guide
  guide.md
Labels: medium priority, New Information, Review request

#195 Fix bad links to VPN logging policies
  guide.md
Labels: high priority, Review request, Bad Link

#197 Update transparency reports
  guide.md
Labels: on hold, medium priority, Information Update

#204 Fix minor formatting issue
  guide.md
Labels: bug

#208 Adding link to an endorsed LINDDUN video
  guide.md
Labels: medium priority, New Information, Review request

#209 Update Git issue template and donation link
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/documentation.md
Labels: low priority

#212 (Large PR, Ready for final review) Getting rid of Archive.org , Wikiless , Nitter , Invidious cross-references
  guide.md
Labels: enhancement, high priority, Information Update, Delete information, Review request

#213 Update to other messaging apps comparisons charts
  guide.md
Labels: medium priority, Information Update, New Information, Review request

#185 Adds Molly.im in the IMs chart
  guide.md
Labels: medium priority, New Information, Review request

#214 Added caution/warning about Session Messenger
  guide.md
Labels: medium priority, New Information, Review request

#216 Fix missing tag for Molly in chart
  guide.md
Labels: bug, urgent, high priority
