Repository Anon-Planet/thgtoa, pull requests merged in 2022-07, with the labels that each got.

#139 guide: iOS Onion Browser leaking IP
  guide.md
Labels: bug, urgent, Information Update, Review request

#137 guide: Tracking Reduction and Tracking Evasion
  guide.md
Labels: New Information, Review request

#135 guide: add additional OPSEC notes
  guide.md
Labels: medium priority, New Information, Review request

#159 Adding link to the side-channel attack in each route
  guide.md
Labels: high priority, New Information, Review request

#158 Replacement of "When using BTC: bonus ..." section
  guide.md
Labels: medium priority, Delete information, Review request

#147 Make Appendix Z more readable and make it obvious it's step-by-step
  guide.md
Labels: low priority

#161 Add ref to a DEF CON 25 vid about fingerprinting
  guide.md
Labels: medium priority, New Information, Review request

#160 Add item in listing of sites showing your browser fingerprint and fixing typos
  guide.md
Labels: medium priority, Information Update, New Information, Review request

#166 Fix Windows 10/11 links and update browser addons
  guide.md
Labels: high priority, Information Update, Bad Link

#167 Link to Qubes tutorial for installing Windows VMs
  guide.md
Labels: medium priority, New Information, Review request

#172 Update to social links for SEO plugin
  _config.yml
Labels: medium priority, Information Update, Review request

#171 Couple of "we" typos
  guide.md
Labels: low priority, Information Update, Review request

#174 Fix to wrong url pointing to the old pre-org repo
  README.md
Labels: high priority, medium priority, Review request, Bad Link

#176 Small fix on Links page , anonymousplanet.org , added -ng
  links.md
Labels: medium priority, Information Update, Review request

#179 Update of bad links from old repo to org repo
  CONTRIBUTING.md
  guide.md
Labels: medium priority, Information Update, Review request, Bad Link

#178 Adding recommended VPNs logging policies links
  guide.md
Labels: medium priority, New Information, Review request

#175 Removal and fix of some bad links
  guide.md
Labels: medium priority, Delete information, Review request, Bad Link

#173 Added link to countering linguistic analysis
  guide.md
Labels: medium priority, New Information, Review request
